### PR TITLE
different views for bootstrap 3 and 4, fixes #4

### LINKED ISSUE #4: Bootstrap 3 alerts not showing
The class "fade" makes the alert with opacity 0, so it's hidden. Working under bootstrap 4 correctly.

### PR DESCRIPTION
**Pull request by sergix44**
The view bootstrap3.blade.php contains classes for correct fade out in
bootstrap 3, and bootstrap4.blade.php contains correct classes for
bootstrap 4.
Updated readme with examples.

### CODE REVIEW

**Comment by vinkla** [comment]
Would it work if we just added the `in` class to the current view?

**Comment by sergix44** [comment]
Under bootstrap 4, no problems because the  `in` class doesn't exists, but in bootstrap 3 the `show` class add `display: block!important;` and i don't know if in some cases it can cause problems.

**Comment by vinkla** [comment]
Maybe you could try it in Bootstrao 3 and see if it works?

**Comment by sergix44** [comment]
Tested with some spans and large texts under bootstrap 3 and it seems there are no problems

**Comment by vinkla** [comment]
Thanks!

**Comment by vinkla** [comment]
Run `composer update` to get the latest changes.

**Pull request merged**
